apiVersion: v1
kind: Service
metadata:
  name: {{ include "circleci.fullname" . }}
  labels:
    {{- include "circleci.labels" . | nindent 4 }}
spec:
  type: {{ .Values.service.type }}
  ports:
    - port: {{ .Values.service.port }}
      targetPort: http
      protocol: TCP
      name: http
  selector:
    {{- include "circleci.selectorLabels" . | nindent 4 }}

--- 

apiVersion: v1
kind: Service
metadata:
  name: svc-ui
  labels:
    app: circleci1
    #tier: frontend
    #chart: {{ include "circleci.chart" . }}
    #release: {{ .Release.Name }}
    heritage: {{ .Release.Service }}
spec:
  type: {{ .Values.service.type }}
  ports:
  - port: {{ .Values.service.port }}
    protocol: TCP
    targetPort: 80
    name: http
  selector:
    app: circleci1
    #tier: frontend
    #release: {{ .Release.Name }}
---
apiVersion: v1
kind: Service
metadata:
  name: svc-redis-server
  labels:
    app: circleci2
    #tier: cache
    #chart: {{ include "circleci.chart" . }}
    #release: {{ .Release.Name }}
    heritage: {{ .Release.Service }}
spec:
  type: ClusterIP
  ports:
  - port: 6379
  selector:
    app: circleci2
    #tier: cache
    #release: {{ .Release.Name }}
---
apiVersion: v1
kind: Service
metadata:
  name: svc-db
  labels:
    app: circleci3
    #tier: backenddb
    #release: {{ .Release.Name }}
    #chart: {{ include "circleci.chart" . }}
spec:
  type: ClusterIP
  ports:
  - port: 5432
  selector:
    app: circleci3
    #tier: backenddb
    #release: {{ .Release.Name }}
---
apiVersion: v1
kind: Service
metadata:
  name: svc-appserver
  labels:
    app: circleci4
    #tier: middletier
    #release: {{ .Release.Name }}
    #chart: {{ include "circleci.chart" . }}
spec:
  type: ClusterIP
  ports:
  - port: 4567
  selector:
    app: circleci4
    #tier: middletier
    #release: {{ .Release.Name }}
